services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: innoscripta-test-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - composer_cache:/home/developer/.composer/cache
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=testing
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=innoscripta
      - DB_USERNAME=innoscripta
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=predis
      - MESSAGING_DRIVER=redis
    ports:
      - "8000:8000"
    command: ['sleep','infinity']

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: innoscripta
      MYSQL_USER: innoscripta
      MYSQL_PASSWORD: secret
      MYSQL_SSL_DISABLED: true
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
    driver: local
  composer_cache:
    driver: local
