name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: PHP CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          extensions: mbstring, pcntl, gd, intl, pdo_mysql
          tools: composer:2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-suggest

      - name: Run PHPStan (static analysis)
        run: ./vendor/bin/phpstan analyse --memory-limit=1G

      - name: Run Pint (coding style)
        run: ./vendor/bin/pint --test

      - name: Prepare environment and run PHPUnit on runner
        run: |
          # prepare local test env and logs directory on the runner
          cp .env.example .env || true
          php artisan key:generate --ansi || true
          mkdir -p build/logs
          # ensure sqlite database file exists for sqlite testing
          mkdir -p database
          touch database/database.sqlite
          chmod 666 database/database.sqlite
          ./vendor/bin/phpunit --testdox --log-junit build/logs/junit.xml

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: build/logs/junit.xml
